apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.9.3/deploy/static/provider/cloud/deploy.yaml
patches:
  - target:
      kind: Deployment
      name: ingress-nginx-controller # Name of the nginx-ingress-controller Deployment
    patch: | # Use a YAML block for the patch
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: "--enable-ssl-passthrough"
