apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/backend-config: '{"default": "argocd-backend-config"}' #Backend Annotation
    cloud.google.com/neg: '{"ingress": true}' #To use Network Endpoint Groups
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/name: argocd-server
    app.kubernetes.io/part-of: argocd
  name: argocd-server
  namespace: argocd
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  - name: https
    port: 443
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/name: argocd-server
  type: NodePort

# apiVersion: v1
# kind: Service
# metadata:
#   name: argocd-server-service
#   namespace: argocd
#   annotations:
#     cloud.google.com/neg: '{"ingress": true}'
#     cloud.google.com/backend-config: '{"ports": {"http":"argocd-backend-config"}}'
# spec:
#   type: ClusterIP
#   ports:
#   - name: http
#     port: 80
#     protocol: TCP
#     targetPort: 8080
#   selector:
#     app.kubernetes.io/name: argocd-server