apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base
  - argocd-frontend-config.yaml
  - argocd-backend-config.yaml
  - argocd-iap-oauth-client.yaml
  - argocd-cert.yaml
  - argocd-ingress.yaml
patches:
  - path: argocd-server-service.yaml
