apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
  - namespace.yaml
  - ../../../../argo-cd/manifests/ha/cluster-install
patches:
  - path: argocd-cmd-params-cm.yaml
